### ISSUE TITLE
wrong url for release download in quick install

### ISSUE THREAD

**Issue by Masterxilo** [cbg-ethz/V-pipe#114]
https://github.com/cbg-ethz/V-pipe/blob/master/utils/quick_install.sh#L216 is wrong

the url for the tagged version tar archive is (now)

https://github.com/cbg-ethz/V-pipe/archive/refs/tags/v2.99.1.tar.gz

(with **refs/tags**)

and not just

https://github.com/cbg-ethz/V-pipe/archive/v2.99.1.tar.gz

**Comment by DrYak** [comment]
fixed on rubicon in #b8e5c945d27572c0731154304defaf92f7c527c7
can you try it on your mac?
