### ISSUE TITLE
Expose parameters in config file?

### ISSUE THREAD

**Issue by tobiasmarschall** [cbg-ethz/V-pipe#2]
Do we plan to have the parameters used in the various rules exposed in the config file? Or do we envision users who want to change some of them to do this in some other way?

**Comment by SoapZA** [comment]
In progress, we'll push later today. The idea is to have users specify options in a `.ini`-style config file.

**Comment by sposadac** [comment]
Documentation is still work in progress, but user-configurable options are already listed in the [wiki](https://github.com/cbg-ethz/V-pipe/wiki/options) pages
