### ISSUE TITLE
Vicuna error

### ISSUE THREAD

**Issue by mhopken** [cbg-ethz/V-pipe#24]
Hello, 

When I run V-Pipe I get the following error file in the initial consensus folder. The V-Pipe run did not complete. Any assistance would be much appreciated. 

[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index consensus.fasta
[main] Real time: 0.020 sec; CPU: 0.004 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 22 sequences (4752 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 1, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 22 reads in 0.005 CPU sec, 0.005 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 consensus.fasta ../preprocessed_data/R1.fastq ../preprocessed_data/R2.fastq
[main] Real time: 0.007 sec; CPU: 0.008 sec
INFO	2019-10-14 23:36:08	SamToFastq	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    SamToFastq -I mapped.bam -FASTQ cleaned/R1.fastq -SECOND_END_FASTQ cleaned/R2.fastq -VALIDATION_STRINGENCY SILENT
**********

23:36:09.046 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/matt_hopken/software/V-pipe/.snakemake/conda/b85da07e/share/picard-2.21.1-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Oct 14 23:36:09 MDT 2019] SamToFastq INPUT=mapped.bam FASTQ=cleaned/R1.fastq SECOND_END_FASTQ=cleaned/R2.fastq VALIDATION_STRINGENCY=SILENT    OUTPUT_PER_RG=false COMPRESS_OUTPUTS_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false INCLUDE_NON_PF_READS=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Oct 14 23:36:09 MDT 2019] Executing as matt_hopken@abdoserver1 on Linux 4.15.0-51-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.1-SNAPSHOT
[Mon Oct 14 23:36:09 MDT 2019] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=514850816
/bin/bash: line 66: vicuna: command not found

**Comment by DrYak** [comment]
Hello and thank you very much for your bug report.

Sadly, currently the vicuna pathway (creating a _denovo_ consensus) isn't working in V-pipe:
`vicuna` isn't available in bioconda and `mvicuna` works in a slightly different way.

The current recommended approach instead is to provide a _reference_ consensus.
For that you need to create a file `references/cohort_consensus.fasta` containing your reference. For example most of our HIV analysis is using HXB2 as a reference.

If building a denovo consensus is important for your workflow: we're currently considering how to proceed to enable this processing back.

**Comment by mhopken** [comment]
Dr. Yak,

Thank you very much for taking the time to reply. I am very interested in using this pipeline. 
Is there a way to turn off Vicuna? The pipeline did not run to completion as I cannot find SNVs or haplotypes. Perhaps it shut down after Vicuna failed so perhaps I can circumvent the de novo assembly because I already have an assembled genome for all of the samples and during the dry run V-pipe seemed to recognize the .fasta file. I am interested in SNVs and haplotype reconstruction for population genetics.
Thank you again!

**Comment by DrYak** [comment]
Sorry, my post wasn't clear:

> Is there a way to turn off Vicuna?

You need to copy some reference consensus into `references/cohort_consensus.fasta`.

As I mentionned, we use HXB2 as a reference genome when working on HIV, so for us that would be: 

    cp references/HXB2.fasta references/cohort_consensus.fasta

> so perhaps I can circumvent the de novo assembly because I already have an assembled genome for all of the samples and during the dry run V-pipe seemed to recognize the .fasta file.

Yes, this assembled genome would do perfectly. Copy it (or symlink it) into  `references/cohort_consensus.fasta`

> I am interested in SNVs and haplotype reconstruction for population genetics.

Currently, our pipeline can run our [ShoRAH](https://github.com/cbg-ethz/shorah) for both SNVs (`snv = True` in the `[output]` section of the configuration) and for local (window based) haplotype (`local = Ture`). This will produce a list of SNVs (in `variants/minority_variants.tsv`) and of local haplotypes (in _{sample}_`/variants/SNVs/REGION_`_{n}_`/` ). This analysis method is quite robust and has already been well tested.

We also have possibility to run global haplotype reconstruction (`global = True`) and recently we have added [Savage](https://bitbucket.org/jbaaijens/savage/) as the default engine.

I might ask: what exact virus are you analysing ?

**Comment by mhopken** [comment]
Thank you! I will give this a try. 
We are working with influenza A viruses collected from wild birds. We are trying to do haplotype reconstruction (both global and local) for each gene segment individually.

I will let you know if/when I get this to work.
Thank you again for your responsiveness, I really appreciate it.

**Comment by mhopken** [comment]
I got the pipeline to run without Vicuna. However I now have a new problem. During preprocessing most of my reads are lost. I start with over 180k reads and end up with 9. Thus variant calling and haplotype reconstruction fail. I know that there are good reads because I have done trimming and assembly with other methods. I have tried to change the preprocessing parameters but it still does exactly the same thing.
Any thoughts?

**Comment by DrYak** [comment]
Which alignment engine are you using ? (the `aligner = `*{aligner}* parameter in the `[general]` section of the configuration)

Did you select to use bwa (`aligner = bwa`) ?
Or did you let the default, our [ngshmmalign](https://github.com/cbg-ethz/ngshmmalign) (either *aligner* not specified, or explicitly `aligner = ngshmmalign`) ?

If it is the later, it might be that the aligner is hitting an untested case. As I've said before we're mostly working on HIV (which only have a single segment) and our component have mostly been tested against other single segment viruses (e.g.: Epstein Barr), maybe *ngshmmalign* is breaking due to not having been tested against a multi-segmented virus such as influenza. I'll have to check with our PhDs.

We might be interested  in your case, as doing some maintenance on our *ngshmmalign* component is on our roadmap.

Is the data you're analysing public and/or could you be allowed to provide it ?

**Comment by mhopken** [comment]
I used both the default and bwa. But I think the problem is that prinseq is eliminating most of my reads. One thing I tried to change is the mean read length, which in my trimmed files is 135. Prinseq is set at 200 so it might be getting rid of most of my reads. Is there a way to use my trimmed read files and skip Prinseq?

I would be happy to share some data files with you so you can test the pipeline on a segmented virus. I currently have the read files and the assemblies of the gene  segments for each individual sample. If you could let me know how to share the files I can get that moving along. 

Also, I tried to run Savage independently and keep getting a python error. Is this something that you can help with? The most important part of your pipeline for me is the global haplotype reconstruction. 
 
Thanks for all of your help. 
Matt

**Comment by sposadac** [comment]
Sorry for the late reply, you need to include a third column in the `samples.tsv` file specifying the read length, and make sure you use a tab
