### ISSUE TITLE
Example to get people started

### ISSUE THREAD

**Issue by tobiasmarschall** [cbg-ethz/V-pipe#3]
Having a little example with sample files somewhere up front in the README would be nice.

**Comment by DrYak** [comment]
The SARS-CoV-2 version of V-pipe introduces a new tutorial: [how to use V-pipe (specifically for SARS-CoV-2 data)](https://cbg-ethz.github.io/V-pipe/tutorial/sars-cov2/)

**Comment by marcovth** [comment]
I have been running the SARS-2 example on three computers, but all I am getting are empty variance files.

Is there anything obvious I am doing wrong?

Thanks.

fastq-dump --split-3 SRR10903401 
fastq-dump --split-3 SRR10903402

curl -O 'https://raw.githubusercontent.com/cbg-ethz/V-pipe/master/utils/quick_install.sh'
bash quick_install.sh -b sars-cov2 -p ./ENV -w work

mkdir ./ENV/work/samples/
mkdir ./ENV/work/samples/SRR10903401/
mkdir ./ENV/work/samples/SRR10903401/20200102/
mkdir ./ENV/work/samples/SRR10903401/20200102/raw_data/
cp ./SRR10903401_1.fastq ./ENV/work/samples/SRR10903401/20200102/raw_data/wuhan2_R1.fastq
cp ./SRR10903401_2.fastq ./ENV/work/samples/SRR10903401/20200102/raw_data/wuhan2_R2.fastq

mkdir ./ENV/work/samples/
mkdir ./ENV/work/samples/SRR10903402/
mkdir ./ENV/work/samples/SRR10903402/20200102/
mkdir ./ENV/work/samples/SRR10903402/20200102/raw_data/
cp ./SRR10903402_1.fastq ./ENV/work/samples/SRR10903402/20200102/raw_data/wuhan1_R1.fastq
cp ./SRR10903402_2.fastq ./ENV/work/samples/SRR10903402/20200102/raw_data/wuhan1_R2.fastq

cd ./ENV/work/

# samples
# ├── SRR10903401
# │   └── 20200102
# │       └── raw_data
# │           ├── wuhan2_R1.fastq
# │           └── wuhan2_R2.fastq
# └── SRR10903402
#     └── 20200102
#         └── raw_data
#             ├── wuhan1_R1.fastq
#             └── wuhan1_R2.fastq

./vpipe --dryrun
./vpipe --cores 4

**Comment by DrYak** [comment]
After running `./vpipe --dryrun`, you need to open the `samples.tsv` file and make sure it contains:

```
SRR10903401	20200102	150
SRR10903402	20200102	150
```

> **Note**: it's a _tab_ separated value (TSV) file, you need to use the _tab_ key to add the 3rd column with the lenght. This step from the tutorial is mandatory for now, sorry. We're going to simplify it in a future version.

Also, when running `./vpipe --dryrun` it should list the following steps:
```
Job counts:
        count   jobs
        1       all
        2       bwa_align
        2       consensus_sequences
        1       coverage_intervals
        4       extract
        4       gunzip
        1       minor_variants
        2       preprocessing
        1       ref_bwa_index
        2       sam2bam
        1       shorah_regions
        2       snv
        23
```

These are the steps that will actually get executed when running `./vpipe --cores <n>`

**Comment by DrYak** [comment]
**Note** the problem that causes error messages

```
Warning: cannot detect conda environment
```

and 

```
exec -a not found
```

on Debian and Ubuntu Linux distributions (and on WSL1 under Windows 10)
has been fixed and are available in all branches.
