### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by yvanw** [cbg-ethz/V-pipe#68]
Hello,
I am having a first try a V-pipe and it seems that Bio.Alphabet has been removed from BioPython this month, causing an error/crash at the report generation step.

```
Traceback (most recent call last):
  File "/Users/ywenger/vpipe/V-pipe/scripts/assemble_visualization_webpage.py", line 16, in <module>
    from Bio.Alphabet import IUPAC
  File "/Users/ywenger/vpipe/work/.snakemake/conda/c7ff4d0f/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
Best,
Yvan

**Comment by kpj** [comment]
Thanks for reporting this! The bug is now fixed in the `sars-cov2-dev` branch (https://github.com/cbg-ethz/V-pipe/commit/40a79f94b5a6ad5fb02b9c871703fb92897e6369).

**Comment by yvanw** [comment]
Welcome, sorry for not commenting here before, it works like a charm in the new dev branch after your modifications. Thanks !
Best,
Yvan
