### ISSUE TITLE
ResolvePackageNotFound:   - savage=0.4.2

### ISSUE THREAD

**Issue by Jamesped** [cbg-ethz/V-pipe#69]
I always ran into this problem. Any idea?

CreateCondaEnvironmentException:
Could not create conda environment from /Users/jameschen/CloudStation/Bioinform/V-pipe/envs/savage.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - savage=0.4.2

**Comment by kpj** [comment]
It looks like you are on macOS (is this correct?).
`savage` does not provide a bioconda package for macOS (see https://anaconda.org/bioconda/savage).

**Comment by Jamesped** [comment]
I will try haploclique instead.
Thank you.
