### ISSUE TITLE
Error in rule generate_web_visualization

### ISSUE THREAD

**Issue by GoncheDanesh** [cbg-ethz/V-pipe#76]
Hi !
Got this error in rule generate_web_visualization, from the assemble_visualization_webpage.py script on line 16 : 
`from Bio.Alphabet import IUPAC`

> ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

What should I do to correct that ? Should I roll back my version of biopython ? 
Thanks !

**Comment by kpj** [comment]
There's already a fix for this in the `sars-cov2-dev` branch, but it hasn't made it to `master` so far (see also #68).
For now I'd recommend using that branch.
