### ISSUE TITLE
Conda not installed in standard location

### ISSUE THREAD

**Issue by jeffkimbrel** [cbg-ethz/V-pipe#86]
I am working on a server where conda and activate are not in a central location, and therefore snakemake isn't able to load up the environments, giving a `/usr/bin/bash: /usr/bin/activate: No such file or directory` error. The snakemake envs load up fine if I do it myself.

```
Activating conda environment: /XXX/V-pipe/.snakemake/conda/3d1013d0
/usr/bin/bash: /usr/bin/activate: No such file or directory

# but this loads it up fine
conda activate /XXX/V-pipe/.snakemake/conda/3d1013d0
```

How can I adjust the snakemake or the `init_project.sh` to use `conda` or `conda activate` from a different location than `/usr/bin/activate`? 

I do have `--use-conda` in my call:

```
./vpipe --dryrun --use-conda
./vpipe --cores 24 --use-conda
```

Thanks.

**Comment by jeffkimbrel** [comment]
I've noticed I do indeed get a warning when initializing:

```
$ ./init_project.sh
Warning: cannot detect conda environment
V-pipe project initialized!

Create and populate 'references' and 'samples' directories or adjust vpipe.config.
Then, use ./vpipe to run V-pipe.
```

It looks like if your conda isn't in a sister directory (to the working directory) called `miniconda3`, then it won't activate properly...

https://github.com/cbg-ethz/V-pipe/blob/7224c383c0b3ad8e98a4211b319fd32256d10bdc/init_project.sh#L59

**Comment by DrYak** [comment]
> It looks like if your conda isn't in a sister directory (to the working directory) called miniconda3, then it won't activate properly...

Yes, it's geared toward simplified installation, e.g.: people who follow [this tutorial](https://cbg-ethz.github.io/V-pipe/tutorial/sars-cov2/) and [thus use the installer](https://github.com/cbg-ethz/V-pipe/blob/master/utils/quick_install.sh).

The installer will setup exactly this way.

Until now we had either users who are extremely fluent at bioconda and snakemake and setup everything on their own. Or user following the tutorial and got it installed this.
I had the plan to add an option to `init_project.sh` so user can either specify the path to their installation (or can remove automatic activation of conda), I just never got to do it.

In you case, the simplest quickest work-around would be to edit the [`vpipe` script which was created by the `init_project.sh` (see this linked examples)](https://github.com/cbg-ethz/pangolin/blob/master/working/vpipe) and fix the activation.

I'll try to find some time introduce proper options in the script.

**Comment by jeffkimbrel** [comment]
Thanks for your quick reply. I hadn't seen the other tutorial and was only looking at the readme and wiki here.

Looking at the modified `vpipe` you linked above, I'm not sure that would fix it as it only affects the initial environment `vpipe` runs in, right? I'm already in an active conda environment to run `vpipe`, it's the subsequent snakemake calls to activate an environment that aren't triggering correctly. 

I am not a snakemake expert, but I would like it to call `/XXX/anaconda3/bin/activate` rather than `/usr/bin/activate` when running each steps of the workflow.

**Comment by DrYak** [comment]
> I'm already in an active conda environment to run vpipe, it's the subsequent snakemake calls to activate an environment that aren't triggering correctly.

Oh, sorry. I haven't understood that part.

Though, please be mindful that:
 - snakemake is [under (very) active development](https://github.com/snakemake/snakemake/releases)
 - conda is also evolving
 - and that [bioconda requires a very specific channel order for optimum function](https://bioconda.github.io/user/install.html#set-up-channels) (if it is out-of-order it might pull the wrong version of dependencies in). (*)
  
As such if your current main conda environment is out-of-date, you might have problem running V-pipe.
 
If you want to keep you current environment, you could create a new separate conda env with snakemake and conda in it:
```bash
conda create -n v-pipe  --channel conda-forge --channel bioconda snakemake-minimal conda
```
- pay attention to have conda-forge channel take precedence over bioconda, either by ordering the options as above, or [running the commands suggested by bioconda](https://bioconda.github.io/user/install.html#set-up-channels)
- it helps snakemake to autodetect conda if it is installed in the same directory (i.e.: in the same environment).

Once this is done, you could edit your `v-pipe` script to have it automatically load this new environment.

This should solve most of the problems preventing snakemake and conda to cooperate.

---
 
 (*) - among other the [wiki written by the former developpers was partially incorrect](https://github.com/cbg-ethz/V-pipe/wiki/getting-started#install-snakemake), I fixed it.

**Comment by jeffkimbrel** [comment]
OK, thanks. I appreciate it. We do have a somewhat old version of conda (4.5.12). Further, I am running everything inside slurm commands, so my user environment (`~/.bashrc`, etc) isn't necessarily the same as the machine the code will get run on. 

There may be too many layers to get this conda thing to work right now. We do have a singularity version working, so I think I will turn to that. 

Thanks for your help, I think we can close this issue for now.

**Comment by DrYak** [comment]
we are indeed thinking about producing complete self contained (single) containers.

also recent versions of snakemake support running the individual rules with Singularity (and building the individual containers using conda).
